name = "nichegeniusproxy"
main = "worker.js"
compatibility_date = "2024-12-01"

[vars]
# This is a non-sensitive variable.
# You can use it to toggle things if needed.
ENVIRONMENT = "production"

[[ratelimits]]
binding = "RATE_LIMITER"
namespace_id = "1001" # any integer ID
# This limits each IP to 100 requests every 60 seconds
simple = { limit = 100, period = 60 }